name: Generate Keystore
on: workflow_dispatch
jobs:
  keygen:
    runs-on: ubuntu-latest
    steps:
      - name: Generar keystore
        run: |
          keytool -genkey -v \
            -keystore crt-lineas-release.jks \
            -alias crt-lineas-key \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass vsBMpd0kqsalfN&i \
            -keypass vsBMpd0kqsalfN&i \
            -dname "CN=Six-Seven, OU=CRT Lineas, O=Six-Seven, L=Mexico, ST=Mexico, C=MX"
          echo "=== KEYSTORE_BASE64 ==="
          base64 crt-lineas-release.jks
          echo "=== FIN ==="
