name: Generate Keystore
on: workflow_dispatch
jobs:
  keygen:
    runs-on: ubuntu-latest
    steps:
      - name: Generar keystore
        run: |
          keytool -genkey -v \
            -keystore crt-lineas-release.jks \
            -alias crt-lineas-key \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass vsBMpd0kqsalfNi \
            -keypass vsBMpd0kqsalfNi \
            -noprompt \
            -dname "CN=SixSeven, OU=CRTLineas, O=SixSeven, L=Mexico, ST=Mexico, C=MX"
          echo "=== KEYSTORE_BASE64 ==="
          base64 -w 0 crt-lineas-release.jks
          echo ""
          echo "=== FIN ==="
